---
- name: Install wordpress
  become: true
  become_user: root
  remote_user: admin
  hosts: tag_application_wordpress
  vars:
    apache_domain: "{{ inventory_hostname }}"
    apache_docroot: /var/www/wordpress/
  tasks:

  - name: Install LAMP packages
    become: true
    apt:
      name="{{ item }}"
      update_cache=yes state=latest
    with_items:
    - libapache2-mod-php5
    - php5-mysql
    - mysql-server
    - python-pymysql
    - python-mysqldb
    - unzip

  - name: Download latest WordPress release
    get_url:
      url: http://wordpress.org/latest.zip
      dest: /tmp/wordpress-latest.zip

  - name: Extract WordPress into /var/www
    unarchive:
      src: /tmp/wordpress-latest.zip
      dest: /var/www/
      remote_src: true

  - name: Create MySQL database
    mysql_db:
      name: "wordpress"
      state: present

  - name: Create MySQL User with Grants
    mysql_user:
      name: "wordpress"
      password: "strasneSloziteHeslo"
      priv: "wordpress.*:ALL"

  - name: Copy Wordpress Config
    copy:
      src: /etc/ansible/files/wp-config.php
      dest: /var/www/wordpress/wp-config.php

  - name: Set Config Variables (password)
    replace:
      dest: /var/www/wordpress/wp-config.php
      regexp: "password_here"
      replace: "strasneSloziteHeslo"
      backup: yes

  - name: Set Config Variables (username_here)
    replace:
      dest: /var/www/wordpress/wp-config.php
      regexp: "username_here"
      replace: "wordpress"
      backup: yes

  - name: Set Config Variables (database_name_here)
    replace:
      dest: /var/www/wordpress/wp-config.php
      regexp: "database_name_here"
      replace: "wordpress"
      backup: yes

  - name: Create Apache Vhost
    template:
      src: /etc/ansible/templates/apache_vhost.j2
      dest: /etc/apache2/sites-enabled/wordpress.conf

  - name: Restart Apache2
    become: true
    service: name=apache2 state=restarted




